### ISSUE TITLE
Nothing to show

### ISSUE THREAD

**Issue by QIanGua** [hkgnp/logseq-keywordfrequency-plugin#1]
Hello, I appreciate this plugin. 
But after I install the newest version 1.2   from the default  plugin market, it show nothing.
I am willing to provide any useful clues.

## Some information
- **OS**: macOS Monterey Version 12.2.1
- **Logseq**: Version 0.6.3

<img width="551" alt="image" src="https://user-images.githubusercontent.com/7362290/159149173-782c4809-ea7e-46a3-9c42-b2eafa9563eb.png">

**Comment by benjypng** [comment]
Hi, you need to start typing some items below that block in order for the plugin to start rendering.

**Comment by QIanGua** [comment]
OMG. Thanks!
